// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_e2AeyXkjp4VW3-NbVmZG-V7VONNMqvY',
    appId: '1:714872165171:web:1b07188ea5236f196e2446',
    messagingSenderId: '714872165171',
    projectId: 'ppamproto-439623',
    authDomain: 'ppamproto-439623.firebaseapp.com',
    storageBucket: 'ppamproto-439623.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR4ldU7EJWPCCZNGHuBwmgINXYYNmaWOI',
    appId: '1:714872165171:android:30cf62e04b46beba6e2446',
    messagingSenderId: '714872165171',
    projectId: 'ppamproto-439623',
    storageBucket: 'ppamproto-439623.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAY5HhVy99EDq-EwXrv_YiCROjzxZjQbc',
    appId: '1:714872165171:ios:34b77a19d6ada3e36e2446',
    messagingSenderId: '714872165171',
    projectId: 'ppamproto-439623',
    storageBucket: 'ppamproto-439623.appspot.com',
    iosBundleId: 'com.asyl.ppamproto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAY5HhVy99EDq-EwXrv_YiCROjzxZjQbc',
    appId: '1:714872165171:ios:34b77a19d6ada3e36e2446',
    messagingSenderId: '714872165171',
    projectId: 'ppamproto-439623',
    storageBucket: 'ppamproto-439623.appspot.com',
    iosBundleId: 'com.asyl.ppamproto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_e2AeyXkjp4VW3-NbVmZG-V7VONNMqvY',
    appId: '1:714872165171:web:f590ded080391c596e2446',
    messagingSenderId: '714872165171',
    projectId: 'ppamproto-439623',
    authDomain: 'ppamproto-439623.firebaseapp.com',
    storageBucket: 'ppamproto-439623.appspot.com',
  );

}