// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoDXRMpfjJiczH8Wj64OSsB1zaHcVw2o4',
    appId: '1:771680864025:web:7114e4cd6643271bdfe788',
    messagingSenderId: '771680864025',
    projectId: 'ppamproto',
    authDomain: 'ppamproto.firebaseapp.com',
    storageBucket: 'ppamproto.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD9KY9tIpr8C28J7X7ZHFM7Ju43MHgwGI',
    appId: '1:771680864025:android:e38417d3b273a5d8dfe788',
    messagingSenderId: '771680864025',
    projectId: 'ppamproto',
    storageBucket: 'ppamproto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpHMvONQYwNNHzFWiWg8PFBoSKsv1NcDo',
    appId: '1:771680864025:ios:50ddecd0850fbee9dfe788',
    messagingSenderId: '771680864025',
    projectId: 'ppamproto',
    storageBucket: 'ppamproto.appspot.com',
    androidClientId: '771680864025-amfge2j78n8uloi9v78re77dfn0idisa.apps.googleusercontent.com',
    iosClientId: '771680864025-j4ss7p0u2c8g1sqbqpqpdrhr3oeab0gu.apps.googleusercontent.com',
    iosBundleId: 'com.asyl.ppamproto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpHMvONQYwNNHzFWiWg8PFBoSKsv1NcDo',
    appId: '1:771680864025:ios:50ddecd0850fbee9dfe788',
    messagingSenderId: '771680864025',
    projectId: 'ppamproto',
    storageBucket: 'ppamproto.appspot.com',
    androidClientId: '771680864025-amfge2j78n8uloi9v78re77dfn0idisa.apps.googleusercontent.com',
    iosClientId: '771680864025-j4ss7p0u2c8g1sqbqpqpdrhr3oeab0gu.apps.googleusercontent.com',
    iosBundleId: 'com.asyl.ppamproto',
  );

}